### PR TITLE
Compass calibration

### PR DESCRIPTION
**Pull request by pmukherj**
Porting kingfisher style compass calibration script to the husky. Ideally, we could have a clearpath general package with this kind of script because it applies to all our platforms with slight modifications on control output  and debug messages.

### CODE REVIEW

**Comment by pmukherj** [comment]
@mikepurvis your thoughts maybe relevant here.

**Comment by mikepurvis** [comment]
I agree about a platform-agnostic version of the calibration. Consider checking such a thing into the imu_compass package. Please also take the opportunity to supply at least some basic docs on the ROS wiki: http://wiki.ros.org/imu_compass (what a magnetic calibration is, how to run it, how to use the file afterward)

Either way, please avoid merging this until there's been support for imu_compass added to husky's _actual_ launchers. It unnecessarily confusing to have a "calibrate_compass" script available which does nothing.

**Comment by pmukherj** [comment]
'Technically', imu_compass is completely robot agnostic. It could be used on an IMU sitting on a desk (which is specifically what that imu_compass/calibrate_compass script is for). So a script that incorporates "control commands" and makes comments about having the right control topic message and the writing of magnetometer parameters to a default /opt/ros/hydro folder maybe inappropriate for imu_compass?

**Comment by mikepurvis** [comment]
Well, all that's in imu_compass right now is `compute_calibration`, the portion which occurs after a bag file has been recorded. A future imu_compass could contain a python module of calibration script building blocks, which would allow a per-platform calibration script to be smaller and simpler.

Anyhow, that's out-of-scope for now. Probably best to just stick with this as-written for the moment.

**Pull request merged**
