### PR TITLE
Added Microstrain device condition

### PR DESCRIPTION
**Pull request by jeff-o**
Looks for an attached Microstrain device and installs the necessary launch files from the microstrain_config directory.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Thanks for adding this!

You'll want to copy the ekf.launch from imu_config into microstrain_config as well—you're also going to need a TF between base_link and the imu. For now, use static_transform_publisher (like the UM6); we'll build it into the URDF later.

@abencz will review and merge.

**Comment by abencz** [comment]
This is begging for a refactor; putting all the common code into a bash function.

**Comment by mikepurvis** [comment]
@abencz Yes, I agree. Ultimately, though, this shouldn't be implemented in bash at all—it should be a Python thing. I'm hoping someday to move the launch- and urdf-globbing capabilities from robot_upstart to a separate package which handles _just_ that aspect. Such a package would be the ideal place for a library of helper functions to live.

Possible timeline could be to prototype using Indigo, release and migrate platforms to it for J-turtle.

**Comment by jeff-o** [comment]
Please review and merge.  I'm tried of installing all this stuff manually. ;)

**Comment by mikepurvis** [comment]
@abencz Please cut a release

**Pull request merged**
