### PR TITLE
Added bringup for ur5 arm

### PR DESCRIPTION
**Pull request by UltronDestroyer**

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
afaik this file will be placed inside the *.d/ folder along side the description.launch. This should make the robot arm be contactable upon spawning.

@mikepurvis  @paulbovbel 

Questions: 

do you want the moveit_planning_execution script be spawned on bringup? This means the user will be able to move the arm after running moveit_rviz.launch. If not, they'll have to run the planning_execution script first before running moveit_rviz.launch. Really just a user experience question here.

**Comment by jeff-o** [comment]
Does the node crash if the arm can't be contacted (e.g. is not powered on,
is still busy initializing, is at a different IP address)?

On Wed, Feb 25, 2015 at 3:34 PM, Devon Ash notifications@github.com wrote:

> afaik this file will be placed inside the *.d/ folder along side the
> description.launch. This should make the robot arm be contactable upon
> spawning.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/husky/husky_bringup/pull/9#issuecomment-76050280.

## 

Jeff Schmidt
System Integration Technologist
Clearpath Robotics
Phone: 519-513-2416

**Comment by UltronDestroyer** [comment]
Let me check that.

@jeff-o 

Yes, the socket returns "No route to host" on giving a wrong/incorrect IP. 
It also crashes if it is busy initializing/or turning on. 

The driver node only successfully launches when the robot has been "started" using the interface. Do we have a workaround for this?

**Comment by paulbovbel** [comment]
Typical workflow for 'highlevel' applications like navigation is, robot starts, then start the 'highlevel' launch, then start the visualization launch. @TheDash, would that make sense for hardware->moveit->viz bringup from your perspective?

Also, the installation logic is in https://github.com/husky/husky_bringup/blob/indigo-devel/scripts/install. Is there any reasonable way to detect the presence of the arm in the system when running the script, and then install the launch files? Otherwise will need additional instructions for http://wiki.ros.org/husky_bringup/Tutorials/Install%20Husky%20Software and http://wiki.ros.org/husky_bringup/Tutorials/Customize%20Husky%20Configuration.

**Comment by UltronDestroyer** [comment]
@paulbovbel 

So, you mean, only call the arm driver bringup once the /dev/ rule has been detected by the computer? (is this dynamic or static, does it run once at runtime.. if so I don't see how this would be different than us manually putting the launch file inside the *.d/ folder. This seems logical otherwise the driver will crash, but in addition, the driver will have to be ready to "start" as well. If we don't have a workaround for that, we'll have to do that.

**Comment by mikepurvis** [comment]
The arm is ethernet-connected, so it's trickier to detect than a plugged-in USB device. I've looked into it a bit, and the best we could really do is try to ping a known IP.

The other business about handling power-on calibration and so-on is a separate matter.

**Comment by UltronDestroyer** [comment]
Power on calibration? When the robot turns on, it doesn't appear to me to go through a movement sequence. Is that perhaps with an older model?

**Comment by jeff-o** [comment]
Exactly.  The arm is an IP device, and usually takes much longer to get
ready than the host computer.  On top of that, if the arm starts up with
its e-stop enabled, it will be possible to ping it but not control it.

Since it's an IP device and you need to specify its IP in the launch file,
you already know which IP to ping test.  If it passes the ping test,
repeatedly query the arm for some sign that it is ready to be commanded.  I
do no know what that query should be.

Older models do a power-on initialization sequence where each joint moves
by a few degrees.  New arms have absolute encoders so don't move, but are
still subject to the longer boot time and the starting in an e-stop
condition.

On Wed, Feb 25, 2015 at 4:04 PM, Mike Purvis notifications@github.com
wrote:

> The arm is ethernet-connected, so it's trickier to detect than a
> plugged-in USB device. I've looked into it a bit, and the best we could
> really do is try to ping a known IP.
> 
> The other business about handling power-on calibration and so-on is a
> separate matter.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/husky/husky_bringup/pull/9#issuecomment-76057476.

## 

Jeff Schmidt
System Integration Technologist
Clearpath Robotics
Phone: 519-513-2416

**Comment by UltronDestroyer** [comment]
Hmm.. will we have a hard-wired e-stop for the arm? (is it going to be built into our existing e-stop?). I'm guessing the C++ Api that they provided will give me access to change those values.

**Comment by jeff-o** [comment]
Typically I connect the "door switch" input to the robot base's e-stop
system.  If an e-stop is triggered on the robot base, it stops the arm but
does not e-stop it.  This way, when the e-stop condition is cleared the arm
is free to continue moving without requiring the user to manually clear the
e-stop condition using the pendant.  Of course, a customer may very well
request that the e-stop input be used instead of the door switch.

The arm will be in a "stopped" mode until it is ready to be commanded.  It
may also stop itself if any of its joints senses an over-torque condition.

On Wed, Feb 25, 2015 at 4:14 PM, Devon Ash notifications@github.com wrote:

> Hmm.. will we have a hard-wired e-stop for the arm? (is it going to be
> built into our existing e-stop?). I'm guessing the C++ Api that they
> provided will give me access to change those values.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/husky/husky_bringup/pull/9#issuecomment-76060654.

## 

Jeff Schmidt
System Integration Technologist
Clearpath Robotics
Phone: 519-513-2416

**Pull request merged**
